### PR TITLE
Update to Akka 2.4

### PR DESCRIPTION
**Pull request by johanandren**
Upgrade to akka 2.4.0-RC1 (and Scala 2.11.7 and SBT 0.13.8), don't merge yet!

### CODE REVIEW

**Comment by ktoso** [comment]
Looks good, no changes needed in the tutorial? (Asking since the words used in the API changed a bit)

**Comment by johanandren** [comment]
No, the tutorial was worded exactly vague enough to not require any changes, except for the doc links.

**Comment by ktoso** [comment]
Cool

**Comment by patriknw** [comment]
I guess similar adjustments as the java template

**Comment by patriknw** [comment]
changed doc links in https://github.com/typesafehub/activator-akka-distributed-workers/pull/15

**Pull request closed without merging**
